NOT_STARTED = 'Not Started'
IN_PROGRESS = 'In Progress'
POSTPONED = 'Postponed'
REMOVED = 'Closed'
COMPLETED = 'Completed'

STATUSES = [
    NOT_STARTED, IN_PROGRESS,
    POSTPONED, REMOVED, COMPLETED]
