from ..shared.display import BLUE, GREEN, GREY, RED, YELLOW


NOT_STARTED = 'Not Started'
IN_PROGRESS = 'In Progress'
POSTPONED = 'Postponed'
REMOVED = 'Closed'
COMPLETED = 'Completed'

STATUSES = [
    NOT_STARTED, IN_PROGRESS,
    POSTPONED, REMOVED, COMPLETED]


STATUS_COLORS = dict()
STATUS_COLORS[NOT_STARTED] = f'[{GREY}]'
STATUS_COLORS[IN_PROGRESS] = f'[{BLUE}]'
STATUS_COLORS[POSTPONED] = f'[{YELLOW}]'
STATUS_COLORS[REMOVED] = f'[{RED}]'
STATUS_COLORS[COMPLETED] = f'[{GREEN}]'
